name: codesnap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  provider: ^6.1.1
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0  # ✅ Added for app icon

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icon.png  # ✅ Your app icon file

# ✅ Flutter Launcher Icons Configuration (single image only)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"   # ✅ One image only (black background)
